FROM {{ item.image }}

ENV container=podman

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      systemd \
      systemd-sysv \
      dbus \
      python3 \
      python3-apt \
      sudo \
      iproute2 \
      ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

STOPSIGNAL SIGRTMIN+3
